server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3307}/${MYSQLDATABASE:petadoption}
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:password}
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

  mail:
    host: smtp.gmail.com
    port: 465
    username: homefurgood25@gmail.com
    password: oupb xeym nzda gtld
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          connectiontimeout: 30000
          timeout: 30000
          writetimeout: 30000
        debug: true
        transport:
          protocol: smtps
        ssl:
          debug: true
          trustStore: ${JAVA_HOME}/lib/security/cacerts
          trustStorePassword: changeit

pet:
  upload:
    base-path: ${UPLOAD_PATH:./pet-uploads}
